version: "3.8"

services:
  web:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/mydb
    depends_on:
      - db
    command: sh -c "npm install && npm run dev"

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
